### PR TITLE
using publicKeyRing if available

### PR DESCRIPTION
**Pull request by RCasatta**
in the case of N-of-M one should be capable to recover funds with only N private keys and M xpub as referenced in https://github.com/bitpay/copay-recovery/issues/54.
In the wallet backup file is saved the total publicKeyRing of the wallet so this patch is using the ring if available to build addresses.

### CODE REVIEW

**Comment by estnomad** [comment]
What is the process like?

**Comment by RCasatta** [comment]
The same as using https://bitpay.github.io/copay-recovery/ but you download the patched repo and open the page locally

**Comment by matiu** [comment]
This is awesome! Thanks a lot for the contribution.

codeACK

**Comment by nsmith543** [comment]
@RCasatta would you be so kind as to explain exactly how I should run this given it hasn't been merged? I went into the Commits section of this request, selected "browse repo as of this point in history", and downloaded a zip. I installed node.js and npm, but I'm not sure how to build it at that point. Am I on the right track?

Thanks

**Comment by RCasatta** [comment]
@nsmith543 the repo works in the browser, no need for node. (git clone the repo or download the zip and open the file index.html).
However, the PR has just been merged, so you could do it on the official web site soon

**Comment by nsmith543** [comment]
@RCasatta thanks for the clarification. I downloaded the zip of the master branch, and when opening src/index.html, I get an empty page. Worst case I can just wait until the hosted site is updated. Really appreciate the contribution by the way, thank you!

**Comment by RCasatta** [comment]
@nsmith543 yes sorry, it's not enough to open the page, you should run `npm start` (as you have seen I don't remember exactly)

**Pull request merged**
