### PR TITLE
PR Fixes issues 93 and 91

### PR DESCRIPTION
**Pull request by morrisonbrett**
PR Fixes issues #93 and #91

### CODE REVIEW

**Comment by morrisonbrett** [comment]
#91

**Comment by JDonadio** [comment]
ACK

**Comment by morrisonbrett** [comment]
@gabrielbazan7 bump

**Comment by morrisonbrett** [comment]
Bump on this one. Is this mergeworthy? @JDonadio @gabrielbazan7

**Comment by morrisonbrett** [comment]
@matiu

**Comment by matiu** [comment]
Thanks!

**Pull request merged**
