### PR TITLE
ignore payload address type if derivation strategy is BIP45

### PR DESCRIPTION
**Pull request by gabrielbazan7**

### CODE REVIEW

**Comment by morrisonbrett** [comment]
Looks great. Thanks for this. This one line fix will help a lot of users.

**Comment by Stoinkler** [comment]
Has this been merged and deployed? I'm still having the issue.

**Comment by martyzigman** [comment]
I was able to get the recovery tool to find the BTG Multi-Signature addresses.  The recovery tool wants me to send the coins to a new destination.  I tried.  It failed.  Seems that the raw transaction sent to https://btgexplorer.com/api/tx/send came back with 

"66: min relay fee not met. Code:-26"

Thus, it's good the coins are there but I need to get more control over the transaction fee to send them on.  Any guidance?  It's really my first time using the recovery tool.

**Comment by morrisonbrett** [comment]
PR #107 addresses this and needs to be merged.

**Comment by morrisonbrett** [comment]
bump

**Comment by shawnp0wers** [comment]
morrisonbrett, does that pull request do anything with BCH (or BCC? I don't know which is proper anymore) mining fees? See my dilemma in the issues, basically I think my transaction is in limbo due to an absurdly low transaction fee. :/

**Comment by robert-claypool** [comment]
@shawnp0wers, #107 only changes the miners fee for BTG: https://github.com/bitpay/copay-recovery/compare/master...robert-claypool:master

**Comment by bhaberle** [comment]
Bump

**Pull request merged**
